#!/usr/local/bin/bash

LEGO=/home/tms/src/lego/bin/legoML
LEGOLIB=/home/tms/lib/libs

unset LEGOLIBS
for dir in `find $LEGOLIB  -name 'lib_*' -prune`
do
  LEGOLIBS=$LEGOLIBS:$dir
done

LEGOPATH=.$LEGOLIBS

echo Remove Object Files...

for file in `find $LEGOLIB -name *.o -print`; 
do
  rm $file
done

echo Regression Testing...

echo > logfile
echo > broken

# --- check files (source then object)


for file in `find $LEGOLIB -name *.l -print`; 
do
  if [ -e ${file%.l}.o ]; then
    if [ ${file%.l}.o -nt $file ]; then
     continue
    fi
  fi
  echo Checking $file
  nam=${file##*/}
  echo Make ${nam%.l} | $LEGO > /tmp/legolog
  if grep "[Ee]rror" /tmp/legolog; then
    cat /tmp/legolog >> logfile
    echo $file >> broken
  fi
done






