/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

typedef unsigned char u_int8_t;
struct ieee80211_scan_entry {
   u_int8_t *se_rsn_ie ;
};

static int giwscan_cb(struct ieee80211_scan_entry  const  *se ) 
{ char buf[(((256 + 1) + 2) - 1) + 5] ;
  int __retres ;
  
  {if (se->se_rsn_ie != (void *)0) {/* STAC: BAD */
                  r_memcpy(buf, se->se_rsn_ie,
                                             (int )*(se->se_rsn_ie + 1) + 2);}
  
  __retres = 0;
  return (__retres);}

}

int main(void) 
{ struct ieee80211_scan_entry se ;
  u_int8_t ie[(((256 + 1) + 2) - 1) + 5 * 2] ;
  int __retres ;
  
  {ie[0] = (u_int8_t )taint();
  se.se_rsn_ie = ie;
  *(se.se_rsn_ie + 1) = (unsigned char )(((((256 + 1) + 2) - 1) + 5 * 2) - 2);
  giwscan_cb((struct ieee80211_scan_entry  const  *)(& se));
  __retres = 0;
  return (__retres);}

}
