/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

extern int ( /* missing proto */  strchr)() ;
char *r_strcpy(char *dest , char const   *src ) ;
void ftpls(char *line ) 
{ int j ;
  int tmp ;
  char user[256] ;
  
  {j = 0;
  while ((int )*(line + j) != 0) {tmp = strchr("-", *(line + j));
    if (! tmp) {break;}
    
    j ++;}
  
  if (j == 2) {if ((int )*(line + j) == ' ') {/* STAC: BAD */
                 r_strcpy(user, line + j);}
    }
  
  return;}

}
int main(void) ;

int main(void) 
{ char out[((256 + 1) + 2) + 2] ;
  int out_l ;
  int dirmode ;
  int npfsize ;
  int c ;
  int __retres ;
  
  {npfsize = 1;
  dirmode = 0;
  out_l = 0;
  out[(((256 + 1) + 2) + 2) - 1] = (char)0;
  top: 
  while (1) {c = taint();
    if (! (c != -1)) {break;}
    
    if (c == '\r') {c = '\n';}
    
    if (c == '\n')
    {if (dirmode) {ftpls(out);}
     else {if (! out_l) {continue;}
     
     if (out_l > npfsize) {dirmode = 1;
       goto top;}
     }
    
    out_l = 0;}
    else {/* STAC: BAD */
    out[out_l] = (char )c;
    out_l ++;
    if (out_l > (((256 + 1) + 2) + 2) - 1) {__retres = -1;
      goto return_label;}
    }
    }
  
  __retres = 0;
  return_label: /* CIL Label */ 
  return (__retres);}

}