/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

typedef int size_t;

char *fb_realpath(char const   *path , char *resolved ) 
{ int rootd ;
  char wbuf[256] ;
  int resultcode ;
  char tmp[256] ;
  int p ;
  int q ;
  int symlinks ;
  int n ;
  int tmp_0 ;
  char *tmp_1 ;
  int tmp_2 ;
  int tmp_3 ;
  char *__retres ;
  
  {strncpy(resolved, path, 256 - 1);
  *(resolved + (256 - 1)) = (char)0;
  loop: 
  q = istrrchr(resolved, '/');
  if (q != -1)
  {p = q + 1;
  if (! (q == 0)) {while (1) {q --;
                     if (q > 0)
                     {if (! ((int )*(resolved + q) == '/')) {break;}
                     }
                     else {break;}
                     }
    
    *(resolved + (q + 1)) = (char)0;
    q = 0;}
  }
  else {p = 0;}
  
  if ((int )*(resolved + p) != 0) {resultcode = nondet_int();
    if (resultcode == 0) {symlinks = 0;
      tmp_0 = nondet_int();
      if (tmp_0) {symlinks ++;
        if (symlinks > 512) {__retres = (char *)((void *)0);
          goto return_label;}
        
        /* STAC: BAD */
        strcpy(tmp, resolved + p);
        n = readlink((char const   *)(tmp), resolved, 256);
        if (n < 0) {__retres = (char *)((void *)0);
          goto return_label;}
        
        *(resolved + n) = (char)0;
        goto loop;}
      }
    }
  
  /* STAC: BAD */
  strcpy(wbuf, resolved + p);
  tmp_1 = getcwd(resolved, 256);
  if (tmp_1 == (void *)0) {__retres = (char *)((void *)0);
    goto return_label;}
  
  if ((int )*(resolved + 0) == '/')
  {if ((int )*(resolved + 1) == 0) {rootd = 1;}
   else {rootd = 0;}
  }
  else {rootd = 0;}
  
  if ((int )wbuf[0] != 0) {{tmp_2 = strlen(resolved);
                            tmp_3 = strlen(wbuf);
                            }
    if (((tmp_2 + tmp_3) + rootd) + 1 > 256) {__retres = (char *)((void *)0);
      goto return_label;}
    
    if (rootd == 0) {strcat(resolved, "/");}
    
    /* STAC: BAD */
    r_strcat(resolved, wbuf);}
  
  __retres = (char *)((void *)0);
  return_label: /* CIL Label */ 
  return (__retres);}

}
int main(void) 
{ char pathname[256] ;
  char resolved[256] ;
  int __retres ;
  
  {pathname[256 - 1] = (char)0;
  resolved[256 - 1] = (char)0;
  fb_realpath((char const   *)(pathname), resolved);
  __retres = 0;
  return (__retres);}

}
