glr.o: glrconfig.h
gramexpl.o: glrconfig.h
gramlex.yy.o: grampar.codes.h
grampar.o: gramast.ast.gen.h
grampar.o: grampar.tab.h
grampar.tab.o: gramast.ast.gen.h
trivlex.o: glrconfig.h
useract.o: glrconfig.h
cc2/cc2.gr.gen.o: glrconfig.h
cc2/cc2main.o: glrconfig.h
cc2/cc2main.o: cc2/cc2.gr.gen.h
