#!/bin/sh
# parse the linux testcases

cd testcases/linux

for fname in *.cpp ; do
  echo "------------ $fname -------------"
  ../../ccgr -tr sizeof ../../cc.bin $fname 2>&1 | tee out/$fname.out
done

