/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

void message_write(char *msg , int len ) 
{ int i ;
  int j ;
  char buffer[256] ;
  int limit ;
  
  {limit = 256 - 1;
  i = 0;
  while (i < len) {j = 0;
    while (1) {if (i < len) {if (! (j < limit)) {break;}
               }
               else {break;}
      
      if (i + 1 < len)
      {if ((int )*(msg + i) == '\n')
       {if ((int )*(msg + (i + 1)) == '.')
        {/* STAC: BAD */
        buffer[j] = *(msg + i);
        j ++;
        i ++;
        /* STAC: BAD */
        buffer[j] = *(msg + i);
        j ++;
        i ++;
        /* STAC: BAD */
        buffer[j] = (char )'.';
        j ++;}
        else {/* STAC: BAD */
        buffer[j] = *(msg + i);
        j ++;
        i ++;}
       }
       else {/* STAC: BAD */
       buffer[j] = *(msg + i);
       j ++;
       i ++;}
      }
      else {/* STAC: BAD */
      buffer[j] = *(msg + i);
      j ++;
      i ++;}
      }
    }
  
  return;}

}

int main(void) 
{ char msg[259] ;
  int __retres ;
  
  {msg[0] = (char )taint();
  message_write(msg, 259);
  __retres = 0;
  return (__retres);}

}
