/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

typedef unsigned int size_t;
extern  __attribute__((__nothrow__)) char *strcpy(char * __restrict  __dest ,
                                                  char const   * __restrict  __src )  __attribute__((__nonnull__(1,2))) ;
extern  __attribute__((__nothrow__)) size_t strlen(char const   *__s )  __attribute__((__pure__,
__nonnull__(1))) ;

int main(void) 
{ char *gecos ;
  char *login ;
  char *buf ;
  char *p ;
  char *bp ;
  int l ;
  char tmp ;
  size_t tmp_0 ;
  char *tmp_1 ;
  int __retres ;
  
  {{tmp = (char )taint();
    *(gecos + 0) = tmp;
    *(login + 0) = tmp;}
  bp = buf;
  if ((int )*gecos == '*') {gecos ++;}
  
  l = 0;
  p = gecos;
  while (1) {if ((int )*p != '\000')
             {if ((int )*p != ',')
              {if ((int )*p != ';') {if (! ((int )*p != '%')) {break;}
               }
               else {break;}
              }
              else {break;}
             }
             else {break;}
    
    if ((int )*p == '&')
    {{tmp_0 = strlen((char const   *)login);
      l = (int )((size_t )l + tmp_0);}}
    else {l ++;}
    
    p ++;}
  
  p = gecos;
  while (1) {if ((int )*p != '\000')
             {if ((int )*p != ',')
              {if ((int )*p != ';') {if (! ((int )*p != '%')) {break;}
               }
               else {break;}
              }
              else {break;}
             }
             else {break;}
    
    if ((int )*p == '&')
    {/* STAC: BAD */
    strcpy((char *)bp, (char const   *)login);
    while ((int )*bp != '\000') {bp ++;}
    }
    else {{{tmp_1 = bp;
           bp ++;}
           
           *tmp_1 = *p;}}
    
    p ++;}
  
  *bp = (char )'\000';
  __retres = 0;
  return (__retres);}

}
