cc.gr.gen.o: cc_tokens.h
cc.gr.gen.o: cc.ast.gen.h
cc_ast_aux.o: cc.ast.gen.h
cc_env.o: cc.ast.gen.h
cc_print.o: cc.ast.gen.h
cc_scope.o: cc.ast.gen.h
cc_tcheck.o: cc.ast.gen.h
cc_tokens.o: cc_tokens.h
ccparse.o: cc.ast.gen.h
lexer.o: cc_tokens.h
lexer.yy.o: cc_tokens.h
main.o: cc_tokens.h
main.o: cc.ast.gen.h
main.o: cc.gr.gen.h
parssppt.o: cc_tokens.h
tlexer.o: cc_tokens.h
const_eval.o: cc.ast.gen.h
