#!/bin/sh
# test-parse mozilla's .i files, without stopping at failures
# use gcc instead of elsa

for fn in `cat /home/scott/bld/mozilla-1.0/allifiles`; do
  echo "--------- $fn"
  echo ./run-g++ -xc++ $fn
  if ./run-g++ -xc++ $fn; then
    echo "$fn: ok"
  else
    echo "$fn: error (code $?)"
  fi
done
