/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

typedef int size_t;

char *fb_realpath(char const   *path , char *resolved ) 
{ int rootd ;
  char wbuf[256] ;
  char *tmp_0 ;
  int tmp_1 ;
  int tmp_2 ;
  char *__retres ;
  
  {wbuf[256 - 1] = (char)0;
  tmp_0 = getcwd(resolved, 256);
  if (tmp_0 == (void *)0) {__retres = (char *)((void *)0);
    goto return_label;}
  
  if ((int )*(resolved + 0) == '/')
  {if ((int )*(resolved + 1) == 0) {rootd = 1;}
   else {rootd = 0;}
  }
  else {rootd = 0;}
  
  if ((int )wbuf[0] != 0) {{tmp_1 = strlen(resolved);
                            tmp_2 = strlen(wbuf);
                            }
    if (((tmp_1 + tmp_2) + rootd) + 1 > 256) {__retres = (char *)((void *)0);
      goto return_label;}
    
    if (rootd == 0) {strcat(resolved, "/");}
    
    r_strcat(resolved, wbuf);}
  
  __retres = (char *)((void *)0);
  return_label: /* CIL Label */ 
  return (__retres);}

}
int main(void) 
{ char pathname[256] ;
  char resolved[256] ;
  int __retres ;
  
  {pathname[256 - 1] = (char)0;
  resolved[256 - 1] = (char)0;
  fb_realpath((char const   *)(pathname), resolved);
  __retres = 0;
  return (__retres);}

}
