/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

typedef unsigned int u_int;
typedef unsigned char u_int8_t;
typedef unsigned int size_t;

static u_int encode_ie(void *buf , size_t bufsize , u_int8_t const   *ie ,
                       size_t ielen , char const   *leader ,
                       size_t leader_len ) 
{ u_int8_t *p ;
  int i ;
  int tmp ;
  u_int __retres ;
  
  {if (bufsize < leader_len) {__retres = 0U;
     goto return_label;}
  
  p = (u_int8_t *)buf;
  memcpy(p, leader, leader_len);
  bufsize -= leader_len;
  p += leader_len;
  i = 0;
  while (1) {if ((size_t )i < ielen) {if (! (bufsize > (size_t )2)) {break;}
             }
             else {break;}
    
    *p = (unsigned char )'x';
    *(p + 1) = (unsigned char )'x';
    p += 2;
    i ++;}
  
  if ((size_t )i == ielen) {tmp = p - (u_int8_t *)buf;}
  else {tmp = 0;}
  
  __retres = (unsigned int )tmp;
  return_label: /* CIL Label */ 
  return (__retres);}

}

int main(void) 
{ u_int8_t buf[(256 + 1) + 2] ;
  u_int8_t ie[(((256 + 1) + 2) - 1) + 5] ;
  char leader[1] ;
  int __retres ;
  
  {{ie[0] = (u_int8_t )taint();
    buf[0] = ie[0];}
  leader[0] = (char )taint();
  encode_ie((void *)(buf), (unsigned int )((256 + 1) + 2),
            (u_int8_t const   *)(ie),
            (unsigned int )((((256 + 1) + 2) - 1) + 5),
            (char const   *)(leader), 1U);
  __retres = 0;
  return (__retres);}

}
