/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

typedef int NSS_STATUS;

static NSS_STATUS _nss_winbind_ipnodes_getbyname(char *name ) 
{ char winsreq[256] ;
  int tmp ;
  NSS_STATUS __retres ;
  
  {tmp = strlen(name);
  /* STAC: BAD */
  r_strncpy(winsreq, name, tmp);
  __retres = 0;
  return (__retres);}

}

int main(void) 
{ char in[256 + 2] ;
  int __retres ;
  
  {in[0] = (char )taint();
  in[(256 + 2) - 1] = (char)0;
  _nss_winbind_ipnodes_getbyname(in);
  __retres = 0;
  return (__retres);}

}
