/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

int parse_expression(char *str ) 
{ int ind ;
  char str2[(256 + 2) + 4] ;
  int __retres ;
  
  {ind = nondet_int();
  if (ind < -1) {__retres = -1;
  goto return_label;}
  else {if (ind >= (256 + 2) + 4) {__retres = -1;
          goto return_label;}
  }
  
  if (ind != -1) {/* STAC: BAD */
  strncpy(str2, str, ind);}
  else {/* STAC: BAD */
  r_strcpy(str2, str);}
  
  __retres = 0;
  return_label: /* CIL Label */ 
  return (__retres);}

}

int main(void) 
{ char A[((256 + 2) + 4) + 1] ;
  int __retres ;
  
  {A[0] = (char )taint();
  A[(256 + 2) + 4] = (char)0;
  parse_expression(A);
  __retres = 0;
  return (__retres);}

}
