/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

typedef int size_t;
typedef short uid_t;

char *realpath(char const   *pathname , char *result , char *chroot_path ) 
{ char curpath[256] ;
  char workpath[256] ;
  char linkpath[256] ;
  char namebuf[256] ;
  int len ;
  int where ;
  int ptr ;
  int last ;
  uid_t userid ;
  char *tmp ;
  char *tmp_0 ;
  int tmp_1 ;
  int tmp_2 ;
  int tmp_3 ;
  int tmp_4 ;
  int tmp_5 ;
  char *__retres ;
  
  {if (result == (void *)0) {__retres = (char *)((void *)0);
     goto return_label;}
  
  if (pathname == (void *)0) {*result = (char)0;
    __retres = (char *)((void *)0);
    goto return_label;}
  
  strcpy(curpath, pathname);
  if ((int const   )*pathname != '/')
  {tmp_0 = getcwd(workpath, 256);
  if (! tmp_0) {userid = geteuid();
    delay_signaling();
    seteuid((short)0);
    tmp = getcwd(workpath, 256);
    if (! tmp) {strcpy(result, ".");
      seteuid(userid);
      enable_signaling();
      __retres = (char *)((void *)0);
      goto return_label;}
    
    seteuid(userid);
    enable_signaling();}
  }
  else {workpath[0] = (char)0;}
  
  where = 0;
  while ((int )curpath[where] != 0) {tmp_1 = strcmp(curpath + where, ".");
    if (! tmp_1) {where ++;
      continue;}
    
    tmp_2 = strncmp(curpath + where, "./", 2);
    if (! tmp_2) {where += 2;
      continue;}
    
    tmp_3 = strncmp(curpath + where, "../", 3);
    if (! tmp_3) {where += 3;
      {last = 0;
       ptr = last;}
      while ((int )workpath[ptr] != 0) {if ((int )workpath[ptr] == '/') {
                                          last = ptr;}
        
        ptr ++;}
      
      /* STAC: BAD */
      workpath[last] = (char)0;
      continue;}
    
    ptr = istrchr(curpath + where, '/');
    if ((int )curpath[ptr] == 0)
    {{tmp_4 = strlen(curpath + where);
      ptr = (where + tmp_4) - 1;}}
    else {/* STAC: BAD */
    curpath[ptr] = (char)0;}
    
    /* STAC: BAD */
    strcpy(namebuf, workpath);
    last = 0;
    while ((int )namebuf[last] != 0) {goto __Cont;
      __Cont: /* CIL Label */ ;
      last ++;}
    }
  
  tmp_5 = nondet_int();
  if (tmp_5 == 1) {len = readlink((char const   *)(namebuf), linkpath, 256);
    if (len <= 0) {__retres = (char *)((void *)0);
      goto return_label;}
    
    /* STAC: BAD */
    linkpath[len] = (char)0;
    if ((int )linkpath[0] == '/') {workpath[0] = (char)0;}
    
    if ((int )curpath[where] != 0) {r_strcat(linkpath, "/");
      /* STAC: BAD */
      r_strcat(linkpath, curpath + where);}
    
    /* STAC: BAD */
    r_strcpy(curpath, linkpath);}
  
  __retres = result;
  return_label: /* CIL Label */ 
  return (__retres);}

}
int main(void) 
{ char pathname[256] ;
  char result[256] ;
  char chroot_path[256] ;
  int __retres ;
  
  {pathname[256 - 1] = (char)0;
  result[256 - 1] = (char)0;
  chroot_path[256 - 1] = (char)0;
  realpath((char const   *)(pathname), result, chroot_path);
  __retres = 0;
  return (__retres);}

}
