rm -fr ./VEX/pub/.svn
rm -fr ./VEX/.svn
rm -fr ./VEX/docs/.svn
rm -fr ./VEX/priv/ir/.svn
rm -fr ./VEX/priv/.svn
rm -fr ./VEX/priv/main/.svn
rm -fr ./VEX/priv/guest-arm/.svn
rm -fr ./VEX/priv/guest-ppc/.svn
rm -fr ./VEX/priv/guest-x86/.svn
rm -fr ./VEX/priv/guest-generic/.svn
rm -fr ./VEX/priv/host-arm/.svn
rm -fr ./VEX/priv/host-ppc/.svn
rm -fr ./VEX/priv/host-x86/.svn
rm -fr ./VEX/priv/guest-amd64/.svn
rm -fr ./VEX/priv/host-generic/.svn
rm -fr ./VEX/priv/host-amd64/.svn
rm -fr ./VEX/test/.svn
rm -fr ./VEX/orig_arm/.svn
rm -fr ./VEX/orig_x86/.svn
rm -fr ./VEX/switchback/.svn
rm -fr ./VEX/orig_amd64/.svn
rm -fr ./VEX/orig_ppc32/.svn
rm -fr ./VEX/auxprogs/.svn
rm -fr ./VEX/unused/.svn
rm -fr ./VEX/useful/.svn
rm -fr ./drd/.svn
rm -fr ./drd/docs/.svn
rm -fr ./drd/tests/.svn
rm -fr ./drd/scripts/.svn
rm -fr ./.svn
rm -fr ./docs/lib/.svn
rm -fr ./docs/xml/.svn
rm -fr ./docs/.svn
rm -fr ./docs/images/.svn
rm -fr ./docs/internals/.svn
rm -fr ./none/.svn
rm -fr ./none/docs/.svn
rm -fr ./none/tests/x86/.svn
rm -fr ./none/tests/.svn
rm -fr ./none/tests/amd64/.svn
rm -fr ./none/tests/linux/.svn
rm -fr ./none/tests/ppc32/.svn
rm -fr ./none/tests/ppc64/.svn
rm -fr ./perf/.svn
rm -fr ./cachegrind/.svn
rm -fr ./cachegrind/docs/.svn
rm -fr ./cachegrind/tests/x86/.svn
rm -fr ./cachegrind/tests/.svn
rm -fr ./tests/.svn
rm -fr ./auxprogs/.svn
rm -fr ./exp-omega/.svn
rm -fr ./exp-omega/docs/.svn
rm -fr ./exp-omega/tests/.svn
rm -fr ./nightly/bin/.svn
rm -fr ./nightly/.svn
rm -fr ./nightly/conf/.svn
rm -fr ./lackey/.svn
rm -fr ./lackey/docs/.svn
rm -fr ./lackey/tests/.svn
rm -fr ./massif/.svn
rm -fr ./massif/docs/.svn
rm -fr ./massif/perf/.svn
rm -fr ./massif/tests/.svn
rm -fr ./callgrind/.svn
rm -fr ./callgrind/docs/.svn
rm -fr ./callgrind/tests/.svn
rm -fr ./coregrind/.svn
rm -fr ./coregrind/m_ume/.svn
rm -fr ./coregrind/m_sigframe/.svn
rm -fr ./coregrind/m_syswrap/.svn
rm -fr ./coregrind/m_dispatch/.svn
rm -fr ./coregrind/m_aspacemgr/.svn
rm -fr ./coregrind/m_coredump/.svn
rm -fr ./coregrind/m_initimg/.svn
rm -fr ./coregrind/m_demangle/.svn
rm -fr ./coregrind/m_debuginfo/.svn
rm -fr ./coregrind/m_replacemalloc/.svn
rm -fr ./coregrind/m_scheduler/.svn
rm -fr ./include/vki/.svn
rm -fr ./include/.svn
rm -fr ./exp-ptrcheck/.svn
rm -fr ./exp-ptrcheck/docs/.svn
rm -fr ./exp-ptrcheck/tests/x86/.svn
rm -fr ./exp-ptrcheck/tests/.svn
rm -fr ./memcheck/.svn
rm -fr ./memcheck/docs/.svn
rm -fr ./memcheck/tests/x86/.svn
rm -fr ./memcheck/tests/.svn
rm -fr ./memcheck/tests/amd64/.svn
rm -fr ./memcheck/tests/linux/.svn
rm -fr ./memcheck/tests/x86-linux/.svn
rm -fr ./helgrind/.svn
rm -fr ./helgrind/docs/.svn
rm -fr ./helgrind/tests/.svn
