/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

void ftpls(char *line ) 
{ int j ;
  int tmp ;
  char user[256] ;
  
  {j = 0;
  while ((int )*(line + j) != 0) {tmp = strchr("-", *(line + j));
    if (! tmp) {break;}
    
    j ++;}
  
  if (j == 2) {if ((int )*(line + j) == ' ') {/* STAC: BAD */
                 r_strcpy(user, line + j);}
    }
  
  return;}

}
extern int ( /* missing proto */  taint)() ;
int main(void) 
{ char in[((256 + 1) + 2) + 2] ;
  int __retres ;
  
  {in[0] = (char )taint();
  in[(((256 + 1) + 2) + 2) - 1] = (char)0;
  ftpls(in);
  __retres = 0;
  return (__retres);}

}
