/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

int fetchsms(char *pdu , int sim ) 
{ char answer[(2 + 2 * 256) + 2] ;
  int position ;
  int beginning ;
  int __retres ;
  
  {answer[0] = (char )taint();
  answer[((2 + 2 * 256) + 2) - 1] = (char)0;
  position = istrstr(answer, "+C");
  if (position == -1) {__retres = 0;
    goto return_label;}
  
  beginning = (position + 2) + 1;
  /* STAC: BAD */
  r_strcpy(pdu, answer + beginning);
  __retres = sim;
  return_label: /* CIL Label */ 
  return (__retres);}

}
int main(void) 
{ char pdu[2 * 256] ;
  int sim ;
  int __retres ;
  
  {sim = 0;
  fetchsms(pdu, sim);
  __retres = 0;
  return (__retres);}

}
