/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

int parse_expression(char *str ) 
{ char *except ;
  char str2[(256 + 2) + 4] ;
  int __retres ;
  
  {except = (char *)strstr(str, "EX");
  if (except)
  {/* STAC: BAD */
  strncpy(str2, str, (unsigned int )(except - str));}
  else {/* STAC: BAD */
  r_strcpy(str2, str);}
  
  __retres = 0;
  return (__retres);}

}

int main(void) 
{ char A[((256 + 2) + 4) + 1] ;
  int __retres ;
  
  {A[0] = (char )taint();
  A[(256 + 2) + 4] = (char)0;
  parse_expression(A);
  __retres = 0;
  return (__retres);}

}
